title: Gustavo C. Visentini
description: Postdoctoral Researcher | AI + Crop Modeling | G×E×M | DSSAT/APSIM | HPC
theme: null
remote_theme: just-the-docs/just-the-docs

url: "https://gustavovisentini.github.io"

search_enabled: true
aux_links:
  "GitHub":
    - "https://github.com/gustavovisentini"

last_edit_timestamp: true
last_edit_time_format: "%b %d, %Y"

color_scheme: light
