title: Gustavo C. Visentini
description: Postdoctoral Researcher | AI + Crop Modeling | HPC
url: https://gustavovisentini.github.io

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: dark

plugins:
  - jekyll-include-cache
